### ISSUE TITLE
what does this project do? 

### ISSUE THREAD

**Issue by RebeWu** [slebok/bibsleigh#4]
Hi, sorry to bother u, I just want to know what does this project do? I am looking for the authers' github of _Mining Duplicate Questions in Stack Overﬂow_ ?

**Comment by grammarware** [comment]
The goals of the project were explained here: http://ceur-ws.org/Vol-1820/paper-06.pdf

If you want the repo of the authors of _Mining Duplicate Questions in Stack Overﬂow_ and the uri's not in the paper, then I'd say try emailing the authors with this question — the emails should be next to their names right on the first page…
